# Site settings
email: info@ltdoil.com
baseurl: "http://designr8.com/LTD-Oilfield-Inc"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: LTD Oilfield Services Inc
description: LTD Oilfield Services Inc -  Oilfield construction and maintainance contractor in Redwater, AB.
url: "http://designr8.com/LTD-Oilfield-Inc"
# twitter_username: 
default_img: 
# Profile settings
name: LTD Oilfield
profile_img:
profile: 
social:
  github: 

# Build settings
include: ["_categories","_img"]
exclude: ["Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
